### ISSUE TITLE
Ship leaving physics range loses connection

### ISSUE THREAD

**Issue by pjwerneck** [toadicus/AntennaRange#5]
Given a ship A carrying a probe B, if you decouple B switch control to it while in physics range (< ~2.2km), then leave physics range, connection is lost and won't be restablished even if within range. You have to switch to A (or some other ship) using the map view and then switch back to B.

Curiously, RemoteTech had the exact same problem in earlier versions.

**Comment by toadicus** [comment]
Resolved by 84cf7552.  Thanks for the report!
